schema:
  - "${PUBLIC_GRAPHQL_API}/preview":
      headers:
        Authorization: ${PRIVATE_GRAPHQL_API_PREVIEW_TOKEN}
documents: './src/lib/graphql/**/*.graphql'
generates:
  src/lib/graphql/types.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unkown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node:
          useTypeImports: true
